
import argparse
import pandas as pd
from pathlib import Path
import sys

# Add src to the Python path to allow for absolute imports
sys.path.append(str(Path(__file__).resolve().parents[1] / "src"))

from utils.evaluation import coherence_ts

def calculate_coherence_for_run(input_parquet_path: str):
    """
    Reads a T-A-S results parquet file, calculates the coherence between
    thesis and synthesis texts, and saves the results to a new parquet file.
    """
    input_path = Path(input_parquet_path)
    if not input_path.exists():
        print(f"Error: Input file not found at {input_path}")
        sys.exit(1)

    print(f"Reading data from {input_path}...")
    df = pd.read_parquet(input_path)

    # Ensure required columns are present
    required_cols = ["problem_id", "thesis_text", "synthesis_text"]
    if not all(col in df.columns for col in required_cols):
        print(f"Error: Input file must contain the columns: {required_cols}")
        sys.exit(1)

    print("Calculating coherence for each problem...")
    coherence_scores = []
    for index, row in df.iterrows():
        problem_id = row["problem_id"]
        print(f"  - Processing {problem_id}...")
        try:
            score = coherence_ts(row["thesis_text"], row["synthesis_text"])
            coherence_scores.append(
                {"problem_id": problem_id, "coherence_score": score}
            )
        except Exception as e:
            print(f"    Could not calculate coherence for {problem_id}: {e}")
            coherence_scores.append(
                {"problem_id": problem_id, "coherence_score": None}
            )

    coherence_df = pd.DataFrame(coherence_scores)

    # Calculate and print aggregated metrics
    print("\n--- Coherence Metrics ---")
    mean_coherence = coherence_df["coherence_score"].mean()
    p50_coherence = coherence_df["coherence_score"].median()
    p90_coherence = coherence_df["coherence_score"].quantile(0.9)

    print(f"Mean: {mean_coherence:.4f}")
    print(f"Median (p50): {p50_coherence:.4f}")
    print(f"90th Percentile (p90): {p90_coherence:.4f}")

    # Save results to a new parquet file
    run_id = df["run_id"].iloc[0]
    output_dir = Path("analytics/parquet")
    output_dir.mkdir(parents=True, exist_ok=True)
    output_filename = f"coherence_{run_id}.parquet"
    output_path = output_dir / output_filename

    print(f"\nSaving coherence results to {output_path}...")
    coherence_df.to_parquet(output_path, index=False)
    print("Done.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Calculate coherence from a T-A-S Parquet file."
    )
    parser.add_argument(
        "input_file",
        type=str,
        help="Path to the input Parquet file generated by the T-A-S flow.",
    )
    args = parser.parse_args()

    calculate_coherence_for_run(args.input_file)
