from pathlib import Path

import pandas as pd


def test_parquet_file_content():
    """
    Verifies the content of the 'pilot_50.parquet' file generated by jsonl_to_parquet.py.
    Checks for file existence, row count, and required columns.
    """
    file_path = Path("analytics/parquet/pilot_50.parquet")

    # Check 1: File existence
    if not file_path.exists():
        raise ValueError(f"Parquet file not found: {file_path}")

    df = pd.read_parquet(file_path)

    # Check 2: Row count
    expected_rows = 50
    if len(df) != expected_rows:
        raise ValueError(f"Expected {expected_rows} rows but found {len(df)} in {file_path}")

    # Check 3: Required columns
    required_columns = [
        "question",
        "answer",
        "thesis",
        "antithesis",
        "synthesis",
        "final_answer",
        "success",
    ]
    missing_columns = [col for col in required_columns if col not in df.columns]

    if missing_columns:
        raise ValueError(f"Missing required columns in {file_path}: {missing_columns}")

    print(f"Verification successful for {file_path}:")
    print(f"- Found {len(df)} rows (expected {expected_rows}).")
    print(f"- All required columns are present: {required_columns}.")
